### PR TITLE
Time indexed sequential semantics experiments

### PR DESCRIPTION
**Pull request by satnam6502**
A "note" to check in which illustrates an alternative way to attribute sequential circuits by viewing signals as functions from a time index to a value, rather than as a list of values or stream of values. Next step would be to model a circuit with a loop e.g.. a counter.

### CODE REVIEW

**Review by jadephilipoom — APPROVED** [review]
Very interesting! A couple of thoughts:

1. The inputs to any circuit need to be complete functions from `nat->bool`, which means that their values across all time have to be known at the outset (or, I suppose, we could quantify over all functions from `nat->bool` that have certain values at the first `n` timesteps). In any case, they won't be able to depend on the circuit body.
2. Does this structure assume everything is using the same clock, or is "timestep" a vague enough notion to save us from that restriction?

**Review by blaxill — APPROVED** [review]
Lgtm. It would be interesting to investigate how this performs on larger circuits over larger time steps.

**Comment by blaxill** [comment]
> 2\. Does this structure assume everything is using the same clock, or is "timestep" a vague enough notion to save us from that restriction?

Definitely our first sequential explorations should assume a single clock domain. A timestep increment unassociated to a clock is too vague as `delay` needs to trigger on a defined clock edge. Modelling arbitrary multiple clocks is going to require some thought and possibly restriction.

**Comment by satnam6502** [comment]
Thanks for the great comments. It's not clear how scalable this specific formulation is. Let's experiment.

**Pull request merged**
