### PR TITLE
Add verilator to nix config dependencies

### PR DESCRIPTION
**Pull request by satnam6502**
Trying to fix CI.

### CODE REVIEW

**Comment by satnam6502** [comment]
nix appears to be broken on macOS Catalina which is not helping me to debug!

**Comment by satnam6502** [comment]
I also can't get nix to work on my desktop machine. @blaxill  do you know what I need to change? I thought adding verilator to the nix config file was enough after looking at https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/electronics/verilator/default.nix

**Comment by satnam6502** [comment]
Now, *which* nix file does the CI use? The current nix file or the incoming nix file? Betting it is the current nix file let me merge this and try another PR.

**Comment by blaxill** [comment]
The CI failure was my fault. The CI uses a docker image built from the nix definitions, but CI does not currently auto rebuild the docker image. I'll do this soon, but I've opened #17 to remind myself.

**Pull request merged**
