### PR TITLE
Update arrow FIR example

### PR DESCRIPTION
**Pull request by blaxill**
- Add `mult` prim and use it in FIR example

### CODE REVIEW

**Review by satnam6502 — COMMENTED** [review]
Is there a test for this either in Coq or as an extracted SystemVerilog testbench?

**Comment by satnam6502** [comment]
Please can you add milestone, relevant bug, and priority? I'd like to try and get as much help as I can to help me follow along with what's going on with all the bugs and PRs. I'll add an "Arrow Investigation" project for this. Thank you.

**Comment by blaxill** [comment]
> Is there a test for this either in Coq or as an extracted SystemVerilog testbench?

Yes, in build logs it is the part:

~~~
make[2]: Leaving directory '/workspace/arrow-examples/obj_dir'
obj_dir/Vfir_tb
                  10: tick = 0, in_stream = 1, out_stream = 0
                  20: tick = 1, in_stream = 2, out_stream = 1
                  30: tick = 2, in_stream = 3, out_stream = 4
                  40: tick = 3, in_stream = 4, out_stream = 10
                  50: tick = 4, in_stream = 5, out_stream = 20
                  60: tick = 5, in_stream = 6, out_stream = 30
                  70: tick = 6, in_stream = 7, out_stream = 40
                  80: tick = 7, in_stream = 8, out_stream = 50
                  90: tick = 8, in_stream = 9, out_stream = 60
~~~

> Please can you add milestone, relevant bug, and priority? I'd like to try and get as much help as I can to help me follow along with what's going on with all the bugs and PRs. I'll add an "Arrow Investigation" project for this. Thank you.

It's part of #302

**Review by satnam6502 — APPROVED** [review]
Great! Thank you.

**Pull request merged**
