### PR TITLE
Don't install globally by default

### PR DESCRIPTION
**Pull request by blaxill**

### CODE REVIEW

**Comment by blaxill** [comment]
Please try this PR out and let me know if it creates problems in your environments.

**Review by satnam6502 — APPROVED** [review]

**Comment by satnam6502** [comment]
I've merged and we can revert if required.

**Comment by satnam6502** [comment]
`make clean` and `make` works for me. Thank you.
Should I now do a global uninstall of some things?

**Comment by satnam6502** [comment]
Perhaps I spoke too soon, I get this error in VS Code when I try to step through code:

```coq
From Cava Require Import Kind.
From Cava Require Import Types. (* This fails *)
```

```
Compiled library Cava.Types (in file /Users/satnam/oak-hardware/cava/Cava/Types.vo) makes inconsistent assumptions over library ExtLib.Structures.Monad
Not in proof mode.
```

**Comment by jadephilipoom** [comment]
I uninstalled the dependencies and re-built them, no issues :+1:

**Pull request merged**
