### PR TITLE
Run `make` in parallel mode for presubmit

### LINKED ISSUE #248: Pre-submits take too long
The pre-submit process for PRs takes very long. Can we do anything to speed it up?
I assume some of this is due to the number of git submodules we use?

### PR DESCRIPTION
**Pull request by jadephilipoom**
If it works, fixes #248 

I have no idea if this works, but I need to create a PR for it for the build to run.

### CODE REVIEW

**Comment by blaxill** [comment]
Any luck solving the interdependencies in the makefiles?

**Comment by jadephilipoom** [comment]
> Any luck solving the interdependencies in the makefiles?

I think so, but still hammering out the kinks. Ask me in a little while!

**Comment by jadephilipoom** [comment]
Okay, it works! Here's the rundown of changes:
- use the `-j` argument for `make` to compile Coq proofs in parallel. I used `-j32` because the machine we're building on has 32 vCPUs
- Fixed the link to machine descriptions, which I discovered was broken as I tried to figure out what to pass to `-j`
- Separated `make coq` from `make` so that we don't wait on the Verilator build to compile the Coq proofs
- Changed the `Makefile` targets so that they will wait for their dependencies when run in parallel (most of the complexity is here)

Time differences from most recent build (in #300):

| Build step | Old | New | Diff
|---|---|---|---|
| recover_git_folder | 00:29 | 00:27 | -00:02 |
| cache_dependencies | 01:34 | 01:31 |-00:03|
| build_verilator | 01:52 | 02:04 |+00:12|
| build_third_party | 03:12 | 01:51 |-01:21|
| run_makefile | 04:13 | 01:04* | -3:09 |
| **Total** | **09:36** | **05:01** | **-4.35**|

\* now two separate build steps, just so we can make progress while waiting for build_verilator

**Review by blaxill — APPROVED** [review]
Lgtm, thanks. I've added a follow up issue to cache verilator #308

**Pull request merged**
